### ISSUE TITLE
Exclude some url path to open the apps?

### ISSUE THREAD

**Issue by pangminfu** [airbnb/DeepLinkDispatch#69] opened 2015-11-30 08:09 UTC
hi,

I want to exclude some url path to prevent it open the apps because the content is not available for android app. below is my example url and action:

URL | Action
------------ | -------------
http://www.example.com/ | open app
http://www.example.com/path/to/content | open app
http://www.example.com/pathto/content | open app
http://www.example.com/pathtocontent | open app
http://www.example.com/help | do not open app
http://www.example.com/contactus | do not open app

how can i achieve this using deeplinkdispatch?

I tried airbnb android app it can open app with below url:
https://www.airbnb.com.sg/
https://www.airbnb.com.sg/rooms/4516626
https://www.airbnb.com.sg/s/Seoul--South-Korea?source=ds

but not open:
https://www.airbnb.com.sg/getaways/Singapore?destination=Kuala-Lumpur
https://www.airbnb.com.sg/help

**Comment by felipecsl** [comment] 2015-12-01 19:21
If you don't add `@DeepLink` annotations for them, these URIs will do nothing, that is, they will not launch your app.
Where exactly that is being handled in your app?

**Comment by pangminfu** [comment] 2015-12-02 03:25
I make some changes to the sample project below is my intent filter in manifest file :

```xml
       <activity
            android:name="com.airbnb.deeplinkdispatch.DeepLinkActivity"
            android:theme="@android:style/Theme.NoDisplay">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https" android:host="www.airbnb.com.sg" />
            </intent-filter>
        </activity>
```

below is my only deeplink annotation in the sample app.(i removed all other deeplink annotation) :

```java
@DeepLink("https://www.airbnb.com.sg/rooms/{arbitraryNumber}")
public class MainActivity extends AppCompatActivity {
  private static final String ACTION_DEEP_LINK_METHOD = "deep_link_method";
  private static final String ACTION_DEEP_LINK_COMPLEX = "deep_link_complex";

  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    if (getIntent().getBooleanExtra(DeepLink.IS_DEEP_LINK, false)) {
      String toastMessage;
      Bundle parameters = getIntent().getExtras();
      if (ACTION_DEEP_LINK_METHOD.equals(getIntent().getAction())) {
        toastMessage = parameters.getString("param1");
      } else if (ACTION_DEEP_LINK_COMPLEX.equals(getIntent().getAction())) {
        toastMessage = parameters.getString("arbitraryNumber");
      } else {
        toastMessage = "class";
      }

      // You can pass a query parameter with the URI, and it's also in parameters, like
      // dld://classDeepLink?qp=123
      if (parameters != null && parameters.getString("qp") != null) {
        toastMessage += " with query parameter " + parameters.getString("qp");
      }

      showToast(toastMessage);
    }
  }
```

generated DeepLinkLoader class :
```java
public final class DeepLinkLoader {
  private final List<DeepLinkEntry> registry = new LinkedList<>();

  void load() {
    registry.add(new DeepLinkEntry("https://www.airbnb.com.sg/rooms/{arbitraryNumber}", DeepLinkEntry.Type.CLASS, MainActivity.class, null));
  }

  DeepLinkEntry parseUri(String uri) {
    for (DeepLinkEntry entry : registry) {
      if (entry.matches(uri)) {
        return entry;
      }
    }
    return null;
  }
}
```
when i call :
```shell
adb shell am start -W -a android.intent.action.VIEW -d "https://www.airbnb.com.sg/help/"
```
and
```shell
adb shell am start -W -a android.intent.action.VIEW -d "https://www.airbnb.com.sg/rooms/12345"
```
it open the app.

what am i wrong? i thought it should open the app only with below url :
https://www.airbnb.com.sg/rooms/{arbitraryNumber}

**Comment by felipecsl** [comment] 2015-12-02 03:30
Did you also copy the `DeepLinkReceiver` class?

**Comment by pangminfu** [comment] 2015-12-02 03:32
i din't make any changes on the deeplink receiver class

```java
public class DeepLinkReceiver extends BroadcastReceiver {
  private static final String TAG = DeepLinkReceiver.class.getSimpleName();

  @Override
  public void onReceive(Context context, Intent intent) {
    String deepLinkUri = intent.getStringExtra(DeepLinkActivity.EXTRA_URI);

    if (intent.getBooleanExtra(DeepLinkActivity.EXTRA_SUCCESSFUL, false)) {
      Log.i(TAG, "Success deep linking: " + deepLinkUri);
    } else {
      String errorMessage = intent.getStringExtra(DeepLinkActivity.EXTRA_ERROR_MESSAGE);
      Log.e(TAG, "Error deep linking: " + deepLinkUri + " with error message +" + errorMessage);
    }
  }
}
```

**Comment by felipecsl** [comment] 2015-12-02 03:50
ok your assumption is correct, it should only open the app with any URI that matches `https://www.airbnb.com.sg/rooms/{arbitraryNumber}`
I'm not sure what is going on. Do you have the Airbnb app installed? I'd recommend using a different hostname for testing, since the Airbnb app is gonna handle any www.airbnb.com.sg deep links.

**Comment by pangminfu** [comment] 2015-12-02 03:55
I had Airbnb app installed but now i had uninstalled Airbnb and try again the result is the same and i had tried to change to other hostname, the result is the same also

**Comment by felipecsl** [comment] 2015-12-02 04:04
OK you can try to see what's going on by attaching a debugger and stepping into `DeepLinkActivity.onCreate()`. In there you should be able to see exactly which activity it is launching and with which arguments. Can you try to do that and let me know what you find out?

**Comment by pangminfu** [comment] 2015-12-02 05:37
Sorry my bad, the sample project is actually working, I had stepping into DeepLinkActivity.onCreate(), i found out that the DeepLinkActivity actually will call finish() if the entry is equal to null to close the app. am i correct?

the reason why i said it was not working previously was because of i keep seeing the sample project app icon in the pop up dialog when i call ``` adb shell am start -W -a android.intent.action.VIEW -d "https://www.exampleasd.com/help ``` 

but previously when i got Airbnb installed and using www.airbnb.com.sg as the hostname i cant see the airbnb icon from the popup dialog with below url

https://www.airbnb.com.sg/getaways/Singapore?destination=Kuala-Lumpur
https://www.airbnb.com.sg/help

but with the same url i can see my sample project icon

**Comment by felipecsl** [comment] 2015-12-02 05:40
Yep, if no entry is found (not a match), DeepLinkActivity finishes and nothing happens. 
Apparently it's working as intended here. Closing.

**Closed by felipecsl** 2015-12-02 05:40 UTC

**Comment by klanjabrik** [comment] 2016-05-24 07:12
@felipecsl I just want to make sure. So the App Chooser still show the application icon, and when user choose the application, it will not open the application?

**Comment by felipecsl** [comment] 2016-05-24 16:28
@klanjabrik correct. If you know that you only want to handle a very specific type of deep links, you can add that to your AndroidManifest.xml `intent-filter` and then if your intent doesn't match your filter, it won't show the App Chooser

**Comment by klanjabrik** [comment] 2016-05-25 12:33
@felipecsl yup, too bad pathPattern doesn't allow application to use negation. Thanks.

**Comment by sudikrt** [comment] 2017-02-25 04:55
how to load deeplink like http://some.com/task?taskid=123455
