### ISSUE TITLE
Cannot apply into multi-modules project

### ISSUE THREAD

**Issue by peacepassion** [airbnb/DeepLinkDispatch#90] opened 2016-04-09 07:26 UTC
The files generated by apt have the file names that are hard coded like following.  

![image](https://cloud.githubusercontent.com/assets/5254121/14402395/febd4dae-fe66-11e5-8bf3-8c75db476050.png)

![image](https://cloud.githubusercontent.com/assets/5254121/14402396/05f0c844-fe67-11e5-8018-4fe211bc482f.png)

As a result, the library can only apply into the project owning only one module app. Otherwise, if applied into one main app and other depend library module, there would be more than one generated files with same names. And that would lead to dex error.

Would you please upgrade the current implementation to support multi-modules project?

**Comment by felipecsl** [comment] 2016-10-09 04:01
This didn't really work well since there is no way to know where the annotation will be generated. Reopening until we have it actually fixed.
I think the best way to go about it is to always enforce the the `@DeepLinkHandler` annotation somewhere and just have the generated classes be based on the annotated one

**Comment by nimengbo** [comment] 2016-10-28 03:20
@felipecsl  Hey guys, I already test this case used `@DeepLinkHandler`, And in multi-module with DeepLink, It's all green .  
What's the problem in this issue answer?

**Comment by felipecsl** [comment] 2016-11-01 04:51
@nimengbo the problem is that having @DeepLink annotations in multiple modules would cause DeepLinkDispatch to generate multiple duplicated classes, since it would generate one DeepLinkActivity for each module and they would all have the same package and same name.
SInce you can't have 2 classes with the exact same name and package name, the dexer would fail with duplicate class definition error.

**Comment by felipecsl** [comment] 2017-02-02 21:29
Fixed in 3.0.0-rc1

**Closed by felipecsl** 2017-02-02 21:29 UTC
Labels: bug
