### ISSUE TITLE
Deeplinkdispatch with Android Annotations - error creating file

### ISSUE THREAD

**Issue by somghosh** [airbnb/DeepLinkDispatch#38] opened 2015-08-03 22:12 UTC
I have a 1 activity project, with Android Annotations (using @EActivity to refer to the activity layout) and I am using DeeplinkDispatch on top of it

Seems like both annotations library don't go so well. If I remove either package, the app runs, but not with both

## Only activity class

	package com.example.android.deeplinktest;

	import android.support.v7.app.AppCompatActivity;
	import android.os.Bundle;
	import android.view.Menu;
	import android.view.MenuItem;
	import android.widget.TextView;

	import com.airbnb.deeplinkdispatch.DeepLink;

	import org.androidannotations.annotations.AfterViews;
	import org.androidannotations.annotations.EActivity;

	@EActivity(R.layout.activity_main)
	@DeepLink("foo://deepLink/{id}")
	public class MainActivity extends AppCompatActivity {

	/*    @Override
	    protected void onCreate(Bundle savedInstanceState) {
	        super.onCreate(savedInstanceState);
	        setContentView(R.layout.activity_main);

	    }*/

	    @AfterViews
	    public void init(){
	        if (getIntent().getBooleanExtra(DeepLink.IS_DEEP_LINK, false)) {
	            Bundle parameters = getIntent().getExtras();

	            String idString = parameters.getString("id");

	            ((TextView)findViewById(R.id.tv)).setText(idString);
	        }
	    }

	}

## Android Manifest

	<?xml version="1.0" encoding="utf-8"?>
	<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	    package="com.example.android.deeplinktest" >

	    <application
	        android:allowBackup="true"
	        android:icon="@mipmap/ic_launcher"
	        android:label="@string/app_name"
	        android:theme="@style/AppTheme" >
	        <activity
	            android:name=".MainActivity_"
	            android:label="@string/app_name" >
	            <intent-filter>
	                <action android:name="android.intent.action.MAIN" />

	                <category android:name="android.intent.category.LAUNCHER" />
	            </intent-filter>
	        </activity>

	        <activity
	            android:name="com.airbnb.deeplinkdispatch.DeepLinkActivity"
	            android:theme="@android:style/Theme.NoDisplay">
	            <intent-filter>
	                <action android:name="android.intent.action.VIEW" />
	                <category android:name="android.intent.category.DEFAULT" />
	                <category android:name="android.intent.category.BROWSABLE" />
	                <data android:scheme="foo" />
	            </intent-filter>
	        </activity>

	    </application>

	</manifest>

## build.gradle

	apply plugin: 'com.android.application'
	apply plugin: 'com.neenbedankt.android-apt'

	android {
	    compileSdkVersion 22
	    buildToolsVersion "22.0.1"

	    defaultConfig {
	        applicationId "com.example.android.deeplinktest"
	        minSdkVersion 17
	        targetSdkVersion 22
	        versionCode 1
	        versionName "1.0"
	    }
	    buildTypes {
	        release {
	            minifyEnabled false
	            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
	        }
	    }
	}

	apt {
	    arguments {
	        androidManifestFile variant.outputs[0].processResources.manifestFile
	        resourcePackageName "com.example.android.deeplinktest"
	    }
	}

	dependencies {
	    compile fileTree(dir: 'libs', include: ['*.jar'])
	    compile 'com.android.support:appcompat-v7:22.2.1'
	    compile 'com.airbnb:deeplinkdispatch:1.3.0'
	    apt 'com.airbnb:deeplinkdispatch-processor:1.3.0'

	    apt "org.androidannotations:androidannotations:3.2"
	    compile 'org.androidannotations:androidannotations-api:3.2'

	}

## Error message

	Information:Gradle tasks [clean, :app:compileDebugSources, :app:compileDebugAndroidTestSources]
	:app:clean
	:app:preBuild UP-TO-DATE
	:app:preDebugBuild UP-TO-DATE
	:app:checkDebugManifest
	:app:preReleaseBuild UP-TO-DATE
	:app:prepareComAndroidSupportAppcompatV72221Library
	:app:prepareComAndroidSupportSupportV42221Library
	:app:prepareDebugDependencies
	:app:compileDebugAidl
	:app:compileDebugRenderscript
	:app:generateDebugBuildConfig
	:app:generateDebugAssets UP-TO-DATE
	:app:mergeDebugAssets
	:app:generateDebugResValues UP-TO-DATE
	:app:generateDebugResources
	:app:mergeDebugResources
	:app:processDebugManifest
	:app:processDebugResources
	:app:generateDebugSources
	:app:processDebugJavaRes UP-TO-DATE
	:app:compileDebugJava
	Note: Resolve log file to /Users/somghosh/Programming/DeepLinkTest/app/build/generated/source/apt/androidannotations.log
	Note: Initialize AndroidAnnotations 3.2 with options {androidManifestFile=/Users/somghosh/Programming/DeepLinkTest/app/build/intermediates/manifests/full/debug/AndroidManifest.xml, resourcePackageName=com.example.android.deeplinktest}
	Note: Start processing for 2 annotations on 4 elements
	Note: AndroidManifest.xml file found with specified path: /Users/somghosh/Programming/DeepLinkTest/app/build/intermediates/manifests/full/debug/AndroidManifest.xml
	Warning:A class activity declared in the AndroidManifest.xml cannot be found in the compile path: [com.airbnb.deeplinkdispatch.DeepLinkActivity]
	Note: AndroidManifest.xml found: AndroidManifest [applicationPackage=com.example.android.deeplinktest, componentQualifiedNames=[com.example.android.deeplinktest.MainActivity_], permissionQualifiedNames=[], applicationClassName=null, libraryProject=false, debugabble=false, minSdkVersion=17, maxSdkVersion=-1, targetSdkVersion=22]
	Note: Found project R class: com.example.android.deeplinktest.R
	Note: Found Android class: android.R
	Note: Validating elements
	Note: Validating with EActivityHandler: [com.example.android.deeplinktest.MainActivity]
	Note: Validating with AfterViewsHandler: [init()]
	Note: Processing root elements
	Note: Processing root elements EActivityHandler: [com.example.android.deeplinktest.MainActivity]
	Note: Processing enclosed elements
	Note: Number of files generated by AndroidAnnotations: 1
	Note: Writting following API classes in project: []
	Note: Generating class: com.example.android.deeplinktest.MainActivity_
	Note: Time measurements: [Whole Processing = 259 ms], [Extract Manifest = 178 ms], [Process Annotations = 32 ms], [Generate Sources = 18 ms], [Find R Classes = 14 ms], [Extract Annotations = 4 ms], [Validate Annotations = 4 ms], 
	Note: Finish processing
	Error:Error creating file
	Note: Start processing for 0 annotations on 3 elements
	Note: Time measurements: [Whole Processing = 0 ms], 
	Note: Finish processing
	Note: Start processing for 0 annotations on 0 elements
	Note: Time measurements: [Whole Processing = 1 ms], 
	Note: Finish processing
	1 warning

**Comment by felipecsl** [comment] 2015-08-04 18:45
looks like we're getting an `IOException` when trying to generate `DeepLinkLoader or DeepLinkActivity`. I'll dig into this

**Comment by felipecsl** [comment] 2015-08-04 19:56
There's something about this androidannotations library that fails compilation when used with DeepLinkDispatch and I can't easily figure out what it is. 
We've been using DeepLinkDispatch in production alongside with many other libraries that do annotation processing (like Dagger, AutoParcel and IcePick, for example) with no problems. 
I'm gonna go ahead and close this issue as I don't think there's a bug here, but feel free to reopen if you find anything relevant about it. I'm tracking the other issue (https://github.com/excilys/androidannotations/issues/1510) in case anything comes up for us.

**Closed by felipecsl** 2015-08-04 19:56 UTC

**Comment by dodgex** [comment] 2015-08-05 09:36
@felipecsl the error itself comes from [DeepLinkProcessor](https://github.com/airbnb/DeepLinkDispatch/blob/master/deeplinkdispatch-processor/src/main/java/com/airbnb/deeplinkdispatch/DeepLinkProcessor.java#L115). I'd invstigate more but at the moment i don't have the time to checkout/debug the reason for the IOException thrown in your code generation. maybe you could test a simple project as discribed by @somghosh but let IOException print its stacktrace/error message.

**Comment by andrewlord1990** [comment] 2015-08-26 15:25
This issue is preventing us from using DeepLinkDispatch, if the issue is coming out of DeepLinkDispatch - DeepLinkProcessor, then why is this issue closed?

**Comment by ray1984** [comment] 2015-09-12 20:06
What about fix?

**Comment by felipecsl** [comment] 2015-09-13 18:21
I'm seeing this in the build output, could be the reason why

```
error: Could not find the AndroidManifest.xml file, going up from path [/Users/felipe_lima/prj/DeepLinkDispatch/sample/build/generated/source/apt/debug] found using dummy file [] (max atempts: file:///Users/felipe_lima/prj/DeepLinkDispatch/sample/build/generated/source/apt/debug/dummy1442168401108)
```

**Comment by felipecsl** [comment] 2015-09-13 20:40
OK this is what you need to make it work. Add it to your build.gradle file:

```
apt {
    arguments {
        androidManifestFile android.applicationVariants.outputs[0].processResources.manifestFile
    }

    processor "com.airbnb.deeplinkdispatch.DeepLinkProcessor"
    processor "org.androidannotations.AndroidAnnotationProcessor"
}
```

**Comment by ray1984** [comment] 2015-09-14 06:26
still doesn't work

**Comment by felipecsl** [comment] 2015-09-14 06:48
Indeed. The discussion is still going on here https://github.com/excilys/androidannotations/issues/1510

**Comment by iHehaDev** [comment] 2016-02-16 13:28
Seems to be related to two Processor will conflict with each other. Still don't have a fix for that yet.

**Comment by amitks2015** [comment] 2018-05-14 02:01
I get ActivityNotFoundException for this very same setup. As I use AndroidAnnotations library, the activity is defined as MainActivity_ in the manifest.

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test/deeplink.DeepLinkActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.test/activities.MainActivity}; have you declared this activity in your AndroidManifest.xml?
> android.content.ActivityNotFoundException: Unable to find explicit activity class {com.test./activities.MainActivity}; have you declared this activity in your AndroidManifest.xml?
> at deeplink.DeepLinkDelegate.dispatchFrom (DeepLinkDelegate.java:134)
> at deeplink.DeepLinkDelegate.dispatchFrom (DeepLinkDelegate.java:50)
> at deeplink.DeepLinkActivity.onCreate (DeepLinkActivity.kt:17) 

This problem seems to be basic, do we have a solution for this? Or we can not use AndroidAnnotations with DeepLinkDispatch?
